language: julia
notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      os: linux
      julia: 1.2
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
